import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/locale-redirect.tsx"),
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("api/uploads/presign", "routes/api.uploads.presign.ts"),
  route("api/uploads/complete", "routes/api.uploads.complete.ts"),
  route(":locale", "routes/marketplace.tsx"),
  route(":locale/themes/:slug", "routes/theme-detail.tsx"),
  route(":locale/themes/:slug/download", "routes/theme-download.ts"),
  route(":locale/themes/:slug/prompt", "routes/theme-prompt.tsx"),
  route(":locale/themes/:slug/comments", "routes/theme-comments.ts"),
  route(":locale/themes/:slug/edit", "routes/themes.$slug.edit.tsx"),
  route(":locale/creators/:handle", "routes/creator-profile.tsx"),
  route(":locale/taxonomies/:dimension/:key", "routes/taxonomy-hub.tsx"),
  route(":locale/auth/sign-in", "routes/auth.sign-in.tsx"),
  route(":locale/me/profile", "routes/me.profile.tsx"),
  route(":locale/me/favorites", "routes/me-favorites.tsx"),
  route(":locale/me/delete-account", "routes/account-delete.tsx"),
  route(":locale/favorite", "routes/favorite.ts"),
  route(":locale/report", "routes/report.ts"),
  route(":locale/upload", "routes/upload.tsx"),
  route(":locale/admin/reports", "routes/admin.reports.tsx"),
  route(":locale/admin/theme", "routes/admin.theme.tsx"),
  route(":locale/admin/user", "routes/admin.user.tsx"),
  route(
    "api/creator-artifacts/:themeId/:version/:artifact",
    "routes/api.creator-artifacts.$themeId.$version.$artifact.ts",
  ),
  route(":locale/terms", "routes/policy-page.tsx", { id: "routes/terms" }),
  route(":locale/privacy", "routes/policy-page.tsx", { id: "routes/privacy" }),
  route(":locale/copyright", "routes/policy-page.tsx", {
    id: "routes/copyright",
  }),
  route(":locale/about", "routes/policy-page.tsx", { id: "routes/about" }),
] satisfies RouteConfig;
